version: '3.8'

services:

  db:
    image: postgres
    environment:      
      POSTGRES_DB: hermes
      POSTGRES_USER: hermes_user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  # migrate:
  #   image: migrate/migrate
  #   volumes:
  #     - ./migrations:/migrations
  #   command: ["-path", "/migrations", "-database",  "postgres://hunt_user:pass@db:5432/hunt?sslmode=disable", "up", "3"]
  #   depends_on:
  #     - db
  
  # cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning
  #   volumes: 
  #     - cache:/data


volumes:
  data:
  # cache:
  #   driver: local